apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnative-bot-stream
  namespace: cn-twitter-stream
  labels:
    app.kubernetes.io/name: cloudnative-bot-stream
    app.kubernetes.io/managed-by: honk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-bot-stream
      app.kubernetes.io/managed-by: honk
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudnative-bot-stream
        app.kubernetes.io/managed-by: honk
    spec:
      containers:
      - name: stream
        image: ko://github.com/cpanato/cloudnative-bot/cmd/twitter-stream
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cloudnative-twitter-config
          mountPath: /tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
        - name: cloudnative-twitter-config
          secret:
            secretName: cloudnative-twitter-config
